version: '3.8'
services:
  app:
    build: .
    container_name: pixelmoon_app
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
volumes:
  mongo_data:
  redis_data:
